//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Xperience.AiraUnified.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class AiraUnifiedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AiraUnifiedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kentico.Xperience.AiraUnified.Resources.AiraUnifiedResources", typeof(AiraUnifiedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIRA Unified.
        /// </summary>
        internal static string AiraUnifiedApplicationPage_Name {
            get {
                return ResourceManager.GetString("AiraUnifiedApplicationPage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit configuration.
        /// </summary>
        internal static string AiraUnifiedConfigurationEditPage_Name {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationEditPage.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the chat..
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_ChatTitle_ExplanationText {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.ChatTitle.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Title.
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_ChatTitle_Label {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.ChatTitle.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Image from a library..
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_Logo_ExplanationText {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.Logo.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_Logo_Label {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.Logo.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative path where the Aira unified is available. The path is relative to the base url of your application. It must start with exactly one &apos;/&apos; and must not end with &apos;/&apos;. It can contain only letters, numbers, dashes and underscores. The path will prefix all other paths created by this integration..
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_RelativePathBase_ExplanationText {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.RelativePathBase.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Path Base.
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_RelativePathBase_Label {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.RelativePathBase.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the smart upload..
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_SmartUploadTitle_ExplanationText {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.SmartUploadTitle.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Upload Title.
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_SmartUploadTitle_Label {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.SmartUploadTitle.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workspace used by the smart uploader..
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_Workspace_ExplanationText {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.Workspace.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string AiraUnifiedConfigurationModel_Workspace_Label {
            get {
                return ResourceManager.GetString("AiraUnifiedConfigurationModel.Workspace.Label", resourceCulture);
            }
        }
    }
}
